### ISSUE TITLE
tests issues

### ISSUE THREAD

**Issue by spth** [Ace17/llvm-cbe#4]
In the directory tests, there is the script "run".
It needs an argument, which is the directory for the llvm-cbe binary (which is not obvious from the error message "Usage: ./run <bin>" one gets when omitting it. I would have rather assumed that I have to give the full path of the llvm-cbe binary instead of the directory it is residing in.
The bigger problem, however is that the file attributes.ll is needed by the script, but it is missing from the git repository.

Philipp

**Comment by Ace17** [comment]
Hi Philipp,
my mistake, I forgot to push the file "attributes.ll". I'll push it asap
(writing from work, at the moment I don't have an internet connection at
home, I'm in the middle of a move)

Users shouldn't need to directly run the "./run" script from the test
directory, they only need to launch the "check" script which will then call
"run" with appropriate arguments. I'm passing the directory instead of the
path to the executable just to be consistent with other projects I manage
where there are several executable files to test. I agree this isn't
usefull in this very repository.

Cheers,
Sebastien

2016-10-10 20:09 GMT+02:00 Philipp Klaus Krause notifications@github.com:

**Comment by Ace17** [comment]
I've added the missing file. Closing this ticket.
